<a href="https://colab.research.google.com/github/Limpapat/Python101/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 101 : NumPy : Work with Array
by Limpapat Bussaban

29/08/2021

[NumPy] Numerical Python https://numpy.org 

[Datacamp] Cheat sheets http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54

In [1]:
import numpy as np

## Data Type in NumPy

Read more: https://numpy.org/doc/stable/reference/arrays.dtypes.html 

```
int     float     bool     string
```

In [2]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

## Creating Arrays

```
np.array(sequence: list or tuple or range)
```

In [3]:
a1 = np.array([1.,3,5])
a2 = np.array(range(1,11))
a3 = np.array(('a', 'b', 'c'))
a4 = np.array([i for i in 'banana'])
print(a1, a2, a3, a4, sep='\n\n')

[1. 3. 5.]

[ 1  2  3  4  5  6  7  8  9 10]

['a' 'b' 'c']

['b' 'a' 'n' 'a' 'n' 'a']


In [4]:
a5 = np.array([1 ,-0.5 ,2 ,True])
print(a5, '\t\t', a5.dtype)

[ 1.  -0.5  2.   1. ] 		 float64


```
np.dtype
np.astype(type)
```

In [5]:
a5 = np.array([1, -0.5, 2, True], dtype=np.dtype(bool))
print(a5, '\t\t', a5.dtype)

[ True  True  True  True] 		 bool


In [6]:
a2 = a2.astype(float)
print(a2, '\t\t', a2.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 		 float64


```
np.zeros(size, dtype=None)
np.ones(size, dtype=None)
np.full(size, fill_value, dtype=None)
```

In [7]:
np.full(10, 10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

```
np.arange([start,] stop, [step,] dtype=None)
np.linspace(start, stop, num=50)
```

In [8]:
np.linspace(10, 12, num=10)

array([10.        , 10.22222222, 10.44444444, 10.66666667, 10.88888889,
       11.11111111, 11.33333333, 11.55555556, 11.77777778, 12.        ])

```
np.random.randint(low, high=None, size=None, dtype=int)
np.random.uniform(low=0.0, high=1.0, size=None)
np.random.rand(shape)
np.random.randn(shape)
np.random.choice(a, size=None, replace=True, p=None)
```

In [9]:
C = np.random.choice(['H', 'T'], size=1000, p=[0.5, 0.5])
(C=='H').sum()

504

## Indexing, Slicing & Filtering

In [10]:
a = np.array([7, 11, 101, 9999, 59, 25, -30, 112, 77, 634])

```
array a:     7     11     101     9999     59     25     -30     112     77     634
+ index:     0      1       2        3      4      5       6       7      8       9
- index:   -10     -9      -8       -7     -6     -5      -4      -3     -2      -1
```

In [11]:
print(a[0], a[-1])

7 634


```
array[start : stop : step]
```

In [12]:
a[0:-1:2]

array([  7, 101,  59, -30,  77])

```
array[index_set]
```

In [13]:
idx = [2*i for i in range(5)]
a[idx]

array([  7, 101,  59, -30,  77])

```
array[condition]
```

In [14]:
a[a > 100]

array([ 101, 9999,  112,  634])

## Math Operators

```
  + - * / % ** //
  == != <> > < >= <=
```

In [15]:
a, b = np.array([1,2]), np.array([3,4])
a+b

array([4, 6])

In [16]:
a + 2 # broadcasting -> https://scipy-lectures.org/_images/numpy_broadcasting.png

array([3, 4])

In [17]:
b==1

array([False, False])

## 2D Arrays

In [18]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

```
          column
        0  1  2
    0 [[1, 2, 3], 
row 1  [3, 5, 6], 
    2  [7, 8, 9]]
```

```
array[row, col]
array[start:stop:step, start:stop:step]
```

In [19]:
# indexing as same 1D

```
ndim
shape
size
```

In [20]:
print(f'ndim: {a.ndim}, shape: {a.shape}, size: {a.size}')

ndim: 2, shape: (3, 3), size: 9


```
view()       # shallow copy
copy()       # deep copy
```

In [21]:
b = a.view()
c = a.copy()
print('---Before---', b, c, sep='\n\n')
print('\n')
a[0] = [-3, -2, -1]
print('---After---', b, c, sep='\n\n')

---Before---

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


---After---

[[-3 -2 -1]
 [ 4  5  6]
 [ 7  8  9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


```
np.reshape()    # shallow copy
np.resize()     # deep copy
```

In [22]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.reshape(a, (1,-1))
c = np.resize(a, (1,9))
print('---Before---', b, c, sep='\n\n')
print('\n')
a[0] = [-3, -2, -1]
print('---After---', b, c, sep='\n\n')

---Before---

[[1 2 3 4 5 6 7 8 9]]

[[1 2 3 4 5 6 7 8 9]]


---After---

[[-3 -2 -1  4  5  6  7  8  9]]

[[1 2 3 4 5 6 7 8 9]]


In [23]:
# Tips
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = a.reshape(-1)
print(b)
b = a.flatten() # equal to .reshape(-1)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [24]:
# Warning!
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = a.reshape(1,-1)
c = a.resize(1,9)
print(b, c, sep='\n\n')

[[1 2 3 4 5 6 7 8 9]]

None


## Basic functions in NumPy arrays

```
sum()
cumsum()
min(), max()
mean()
```

In [25]:
print(' sum: {} \n\n cunsum: {} \n\n min: {} \n\n max: {} \n\n mean: {}'.format(a.sum(), 
                                                                                a.cumsum(), 
                                                                                a.min(), 
                                                                                a.max(), 
                                                                                a.mean()))

 sum: 45 

 cunsum: [ 1  3  6 10 15 21 28 36 45] 

 min: 1 

 max: 9 

 mean: 5.0


```
np.sort()
np.unique()
```

In [26]:
a = np.array([7, 11, 101, 77, 59, 25, -30, 112, 77, 634])
print(' a: \t\t {} \n\n sort: \t\t {} \n\n unique: \t {}'.format(a, np.sort(a), np.unique(a)))

 a: 		 [  7  11 101  77  59  25 -30 112  77 634] 

 sort: 		 [-30   7  11  25  59  77  77 101 112 634] 

 unique: 	 [-30   7  11  25  59  77 101 112 634]


In [27]:
# Tips
a = np.array([[7, 11, 101, 77, 59], 
              [25, -30, 112, 77, 634]])
print(' a: \n{} \n\n sort: \n{} \n\n unique: \n{}'.format(a, np.sort(a), np.unique(a)))

 a: 
[[  7  11 101  77  59]
 [ 25 -30 112  77 634]] 

 sort: 
[[  7  11  59  77 101]
 [-30  25  77 112 634]] 

 unique: 
[-30   7  11  25  59  77 101 112 634]


In [28]:
np.sort(a,axis=0)

array([[  7, -30, 101,  77,  59],
       [ 25,  11, 112,  77, 634]])

```
np.concatenate((a1, a2, ...), axis=0)
np.vstack(tuple)
np.hstack(tuple)
```

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[.4, .3],[.2, .1]])

c1 = np.concatenate((a,b))
c2 = np.concatenate((a,b), axis=1)
print(a, b, c1, c2, sep='\n\n')

[[1 2]
 [3 4]]

[[0.4 0.3]
 [0.2 0.1]]

[[1.  2. ]
 [3.  4. ]
 [0.4 0.3]
 [0.2 0.1]]

[[1.  2.  0.4 0.3]
 [3.  4.  0.2 0.1]]


In [30]:
# a = np.random.rand(10,10,3)
# b = np.random.rand(10,10,3)
# x = np.empty((20,10,3))
# c = np.concatenate((a,b), out=x)
# d = np.concatenate((a,b), axis=0)
# c.shape, d.shape

In [31]:
v = np.vstack((a,b))
h = np.hstack((a,b))
print(a, b, v, h, sep='\n\n')

[[1 2]
 [3 4]]

[[0.4 0.3]
 [0.2 0.1]]

[[1.  2. ]
 [3.  4. ]
 [0.4 0.3]
 [0.2 0.1]]

[[1.  2.  0.4 0.3]
 [3.  4.  0.2 0.1]]


```
np.split(array, indices_or_sections, axis=0)
np.vsplit(array, indices_or_sections)
np.hsplit(array, indices_or_sections)
```

In [32]:
print(np.split(v, 2), np.split(v, 4), sep='\n\n')

[array([[1., 2.],
       [3., 4.]]), array([[0.4, 0.3],
       [0.2, 0.1]])]

[array([[1., 2.]]), array([[3., 4.]]), array([[0.4, 0.3]]), array([[0.2, 0.1]])]


In [33]:
np.vsplit(v,2)

[array([[1., 2.],
        [3., 4.]]), array([[0.4, 0.3],
        [0.2, 0.1]])]

In [34]:
np.hsplit(v,2)

[array([[1. ],
        [3. ],
        [0.4],
        [0.2]]), array([[2. ],
        [4. ],
        [0.3],
        [0.1]])]

In [35]:
x = np.arange(1, 37).reshape(6,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [36]:
np.split(x, [1, 2, 5, 9])

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36]]),
 array([], shape=(0, 6), dtype=int64)]